version: '2'

volumes:
  peergov1.gov.io:
  peertm1.manufacturer.com:
  peertm2.manufacturer.com:
  peertf1.production.com:
  peertf2.production.com:
  peerbb1.retailer.com:
  peerbb2.retailer.com:
  peerts1.warehouse.com:
  peerts2.warehouse.com:
  orderer1.gov.io:
  orderer2.gov.io:
  orderer3.gov.io:

services:

  peergov1.gov.io:
    container_name: peergov1.gov.io
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peergov1.gov.io
      - CORE_PEER_ADDRESS=peergov1.gov.io:13050
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13050
      - CORE_PEER_CHAINCODEADDRESS=peergov1.gov.io:13051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peergov1.gov.io:13050
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peergov1.gov.io:13050
      - CORE_PEER_LOCALMSPID=govMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/gov.io/peers/peergov1.gov.io/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/gov.io/peers/peergov1.gov.io/tls:/etc/hyperledger/fabric/tls
      - ../persistence-data/peergov1.gov.io:/var/hyperledger/production
    ports:
      - 13050:13050

  peertm1.manufacturer.com:
    container_name: peertm1.manufacturer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peertm1.manufacturer.com
      - CORE_PEER_ADDRESS=peertm1.manufacturer.com:9051
      - CORE_PEER_LISTENADDRESS=peertm1.manufacturer.com:9051
      - CORE_PEER_CHAINCODEADDRESS=peertm1.manufacturer.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peertm2.manufacturer.com:9081
      - CORE_PEER_GOSSIP_ENDPOINT=peertm1.manufacturer.com:9051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peertm1.manufacturer.com:9051
      - CORE_PEER_LOCALMSPID=tataMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/manufacturer.com/peers/peertm1.manufacturer.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/manufacturer.com/peers/peertm1.manufacturer.com/tls:/etc/hyperledger/fabric/tls
      - ../persistence-data/peertm1.manufacturer.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peertm2.manufacturer.com:
    container_name: peertm2.manufacturer.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peertm2.manufacturer.com
      - CORE_PEER_ADDRESS=peertm2.manufacturer.com:9081
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9081
      - CORE_PEER_CHAINCODEADDRESS=peertm2.manufacturer.com:9082
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9082
      - CORE_PEER_GOSSIP_BOOTSTRAP=peertm1.manufacturer.com:9051
      - CORE_PEER_GOSSIP_ENDPOINT=peertm2.manufacturer.com:9081
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peertm2.manufacturer.com:9081
      - CORE_PEER_LOCALMSPID=tataMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/manufacturer.com/peers/peertm2.manufacturer.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/manufacturer.com/peers/peertm2.manufacturer.com/tls:/etc/hyperledger/fabric/tls
      - ../persistence-data/peertm2.manufacturer.com:/var/hyperledger/production
    ports:
      - 9081:9081

  peertf1.production.com:
    container_name: peertf1.production.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peertf1.production.com
      - CORE_PEER_ADDRESS=peertf1.production.com:8051
      - CORE_PEER_LISTENADDRESS=peertf1.production.com:8051
      - CORE_PEER_CHAINCODEADDRESS=peertf1.production.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peertf2.production.com:8081
      - CORE_PEER_GOSSIP_ENDPOINT=peertf1.production.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peertf1.production.com:8051
      - CORE_PEER_LOCALMSPID=teafarmMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/production.com/peers/peertf1.production.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/production.com/peers/peertf1.production.com/tls:/etc/hyperledger/fabric/tls
      - ../persistence-data/peertf1.production.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peertf2.production.com:
    container_name: peertf2.production.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peertf2.production.com
      - CORE_PEER_ADDRESS=peertf2.production.com:8081
      - CORE_PEER_LISTENADDRESS=peertf2.production.com:8081
      - CORE_PEER_CHAINCODEADDRESS=peertf2.production.com:8082
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8082
      - CORE_PEER_GOSSIP_BOOTSTRAP=peertf1.production.com:8051
      - CORE_PEER_GOSSIP_ENDPOINT=peertf1.production.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peertf2.production.com:8081
      - CORE_PEER_LOCALMSPID=teafarmMSP
    volumes:
      - /var/run/:/host/var/run/
      - ../crypto-config/peerOrganizations/production.com/peers/peertf2.production.com/msp:/etc/hyperledger/fabric/msp
      - ../crypto-config/peerOrganizations/production.com/peers/peertf2.production.com/tls:/etc/hyperledger/fabric/tls
      - ../persistence-data/peertf2.production.com:/var/hyperledger/production
    ports:
      - 8081:8081

  
  orderer1.gov.io:
    container_name: orderer1.gov.io
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=7050
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/gov.io/orderers/orderer1.gov.io/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/gov.io/orderers/orderer1.gov.io/tls:/var/hyperledger/orderer/tls
      - ../persistence-data/orderer1:/var/hyperledger/production
    ports:
      - 7050:7050

  orderer2.gov.io:
    container_name: orderer2.gov.io
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=7051
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/gov.io/orderers/orderer2.gov.io/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/gov.io/orderers/orderer2.gov.io/tls:/var/hyperledger/orderer/tls
      - ../persistence-data/orderer2:/var/hyperledger/production
    ports:
      - 7051:7051

  orderer3.gov.io:
    container_name: orderer3.gov.io
    extends:
      file: peer-base.yaml
      service: orderer-base
    environment:
      - ORDERER_GENERAL_LISTENPORT=7052
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/gov.io/orderers/orderer3.gov.io/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/gov.io/orderers/orderer3.gov.io/tls:/var/hyperledger/orderer/tls
      - ../persistence-data/orderer3:/var/hyperledger/production
    ports:
      - 7052:7052